/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions`
 */
object Libs {
    /**
     * https://github.com/square/retrofit
     */
    const val converter_moshi: String = "com.squareup.retrofit2:converter-moshi:" +
            Versions.com_squareup_retrofit2

    /**
     * https://github.com/square/retrofit
     */
    const val retrofit: String = "com.squareup.retrofit2:retrofit:" +
            Versions.com_squareup_retrofit2

    const val converter_scalars =
        "com.squareup.retrofit2:converter-scalars:" + Versions.converter_scalars

    /**
     * https://github.com/square/moshi/
     */
    const val moshi: String = "com.squareup.moshi:moshi:" +
            Versions.moshi

    /**
     * https://github.com/square/moshi/
     */
    const val moshi_codegen: String = "com.squareup.moshi:moshi-kotlin-codegen:" +
            Versions.moshi

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_android_extensions: String =
        "org.jetbrains.kotlin:kotlin-android-extensions:" + Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_android_extensions_runtime: String =
        "org.jetbrains.kotlin:kotlin-android-extensions-runtime:" +
                Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_annotation_processing_gradle: String =
        "org.jetbrains.kotlin:kotlin-annotation-processing-gradle:" +
                Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_gradle_plugin: String = "org.jetbrains.kotlin:kotlin-gradle-plugin:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_scripting_compiler_embeddable: String =
        "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:" +
                Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_stdlib: String = "org.jetbrains.kotlin:kotlin-stdlib:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://developer.android.com/studio
     */
    const val com_android_tools_build_gradle: String = "com.android.tools.build:gradle:" +
            Versions.com_android_tools_build_gradle

    const val com_google_android_play_core: String = "com.google.android.play:core:" +
            Versions.com_google_android_play_core

    /**
     * https://square.github.io/okhttp/
     */
    const val logging_interceptor: String = "com.squareup.okhttp3:logging-interceptor:" +
            Versions.okhttp

    /**
     * http://github.com/square/leakcanary/
     */
    const val leakcanary_android: String = "com.squareup.leakcanary:leakcanary-android:" +
            Versions.leakcanary_android

    /**
     * https://developer.android.com/jetpack/androidx
     */
    const val swiperefreshlayout: String = "androidx.swiperefreshlayout:swiperefreshlayout:" +
            Versions.swiperefreshlayout

    /**
     * http://tools.android.com
     */
    const val constraintlayout: String = "androidx.constraintlayout:constraintlayout:" +
            Versions.constraintlayout

    /**
     * https://github.com/airbnb/epoxy
     */
    const val epoxy_processor: String = "com.airbnb.android:epoxy-processor:" +
            Versions.epoxy_processor

    /**
     * https://github.com/airbnb/mvrx
     */
    const val mavericks_testing: String =
        "com.airbnb.android:mavericks-testing:" + Versions.mavericks

    /**
     * https://developer.android.com/jetpack/androidx/releases/recyclerview#1.2.0
     */
    const val recyclerview: String = "androidx.recyclerview:recyclerview:" + Versions.recyclerview

    /**
     * https://developer.android.com/studio
     */
    const val lint_gradle: String = "com.android.tools.lint:lint-gradle:" + Versions.lint_gradle

    /**
     * https://developer.android.com/jetpack/androidx
     */
    const val appcompat: String = "androidx.appcompat:appcompat:" + Versions.appcompat

    /**
     * https://developer.android.com/jetpack/androidx
     */
    const val core_ktx: String = "androidx.core:core-ktx:" + Versions.core_ktx

    /**
     * https://github.com/material-components/material-components-android
     */
    const val material: String = "com.google.android.material:material:" + Versions.material

    const val rxpaper2: String = "com.github.pakoito:RxPaper2:" + Versions.rxpaper2

    /**
     * https://github.com/airbnb/lottie-android
     */
    const val lottie: String = "com.airbnb.android:lottie:" + Versions.lottie

    /**
     * https://github.com/JakeWharton/timber
     */
    const val timber: String = "com.jakewharton.timber:timber:" + Versions.timber

    /**
     * https://developer.android.com/studio
     */
    const val aapt2: String = "com.android.tools.build:aapt2:" + Versions.aapt2

    /**
     * https://github.com/airbnb/epoxy
     */
    const val epoxy: String = "com.airbnb.android:epoxy:" + Versions.epoxy

    /**
     * https://github.com/bumptech/glide
     */
    const val glide: String = "com.github.bumptech.glide:glide:" + Versions.glide

    /**
     * http://junit.org
     */
    const val junit = "junit:junit:" + Versions.junit
    const val ext_junit = "androidx.test.ext:junit:" + Versions.ext_junit
    const val espresso_core = "androidx.test.espresso:espresso-core:" + Versions.espresso_core

    /**
     * http://mockk.io
     */
    const val mockk: String = "io.mockk:mockk:" + Versions.mockk

    /**
     * https://github.com/airbnb/mavericks
     */
    const val mavericks: String = "com.airbnb.android:mavericks:" + Versions.mavericks

    const val hilt_android: String = "com.google.dagger:hilt-android:" + Versions.dagger_hilt
    const val hilt_android_compiler =
        "com.google.dagger:hilt-android-compiler:" + Versions.dagger_hilt
    const val hilt_lifecycle_viewmodel =
        "androidx.hilt:hilt-lifecycle-viewmodel:" + Versions.hilt_lifecycle_viewmodel
    const val hilt_common = "androidx.hilt:hilt-common:" + Versions.hilt_common
    const val hilt_android_testing =
        "com.google.dagger:hilt-android-testing:" + Versions.dagger_hilt
    const val hilt_compiler = "androidx.hilt:hilt-compiler:" + Versions.hilt_compiler
    const val okhttp = "com.squareup.okhttp3:okhttp:" + Versions.okhttp
    const val room_runtime = "androidx.room:room-runtime:" + Versions.room
    const val room_compiler = "androidx.room:room-compiler:" + Versions.room
    const val room_ktx =
        "androidx.room:room-ktx:" + Versions.room // optional - Kotlin Extensions and Coroutines support for Room
    const val lifecycle_livedata_ktx: String =
        "androidx.lifecycle:lifecycle-livedata-ktx:" + Versions.lifecycle_livedata_ktx
    const val lifecycle_viewmodel_ktx =
        "androidx.lifecycle:lifecycle-viewmodel-ktx:" + Versions.lifecycle_viewmodel_ktx
    const val activity_ktx: String = "androidx.activity:activity-ktx:" + Versions.activity_ktx
    const val auto_fill = "androidx.autofill:autofill:" + Versions.auto_fill
    const val navigation_fragment_ktx =
        "androidx.navigation:navigation-fragment-ktx:" + Versions.navigation_fragment_ktx
    const val navigation_ui_ktx =
        "androidx.navigation:navigation-ui-ktx:" + Versions.navigation_ui_ktx

    const val kotlinx_serialization_json =
        "org.jetbrains.kotlinx:kotlinx-serialization-json:" + Versions.kotlinx_serialization
    const val kotlinx_serialization_protobuf =
        "org.jetbrains.kotlinx:kotlinx-serialization-protobuf:" + Versions.kotlinx_serialization
    const val paging_runtime_ktx =
        "androidx.paging:paging-runtime-ktx:" + Versions.paging_runtime_ktx
    const val retrofit_kotlinx_serialization_converter =
        "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter:" + Versions.retrofit_kotlinx_serialization_converter
    const val moshi_kotlin: String = "com.squareup.moshi:moshi-kotlin:" +
            Versions.moshi
    const val kotlinx_coroutines_core = "org.jetbrains.kotlinx:kotlinx-coroutines-core:" + Versions.kotlinx_coroutines_core
    const val kotlinx_coroutines_core_jvm = "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:"+Versions.kotlinx_coroutines_core
}
