/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
    const val com_squareup_retrofit2: String = "2.9.0"

    const val org_jetbrains_kotlin: String = "1.5.10"

    const val com_android_tools_build_gradle: String = "7.0.0"

    const val com_google_android_play_core: String = "1.10.0"

    const val leakcanary_android: String = "2.7"

    const val swiperefreshlayout: String = "1.1.0"

    const val constraintlayout: String = "2.0.4"

    const val epoxy_processor: String = "4.5.0"

    const val recyclerview: String = "1.2.0"

    const val lint_gradle: String = "27.1.3"

    const val appcompat: String = "1.3.0-rc01"

    const val core_ktx: String = "1.6.0-alpha03"

    const val material: String = "1.3.0"

    const val rxpaper2: String = "1.5.0"

    const val lottie: String = "3.7.0"

    const val timber: String = "4.7.1"

    const val aapt2: String = "4.1.3-6503028"

    const val epoxy: String = "4.5.0"

    const val glide: String = "4.12.0"

    const val moshi: String = "1.12.0"

    const val junit: String = "4.13.2"

    const val mockk: String = "1.11.0"

    const val mavericks: String = "2.2.0"

    const val dagger_hilt = "2.37"
    const val lifecycle_livedata_ktx = "2.3.1"
    const val lifecycle_viewmodel_ktx = "2.3.1"
    const val activity_ktx = "1.2.3"
    const val ext_junit = "1.1.2"
    const val espresso_core = "3.3.0"
    const val hilt_lifecycle_viewmodel = "1.0.0-alpha03"
    const val hilt_common = "1.0.0-alpha03"
    const val hilt_compiler = "1.0.0-beta01"
    const val okhttp = "4.9.1"
    const val converter_scalars = "2.6.0"
    const val room = "2.3.0"
    const val auto_fill = "1.0.0"
    const val navigation_fragment_ktx = "2.3.5"
    const val navigation_ui_ktx = "2.3.5"
    const val navigation_safe_args_gradle_plugin = "2.3.5"
    const val kotlinx_serialization = "1.2.0"
    const val paging_runtime_ktx = "3.0.0-beta01"
    const val retrofit_kotlinx_serialization_converter = "0.8.0"
    const val kotlinx_coroutines_core = "1.4.3"
}
